package friends_coursework.user.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import friends_coursework.config.*;

@DynamoDBTable(tableName=Config.DYNAMODB_USERS_TABLE_NAME)
public class User
{
	private  String user_id;
	private  String user_name;
	private  Date last_login;

	public User()
	{
	} //end method

	public User(String user_name)
	{
		this.setUsername(user_name);
	} //end method

	@DynamoDBHashKey(attributeName="user_id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return user_id;
	} //end method

	public void setId(String user_id) {
		this.user_id = user_id;
	} //end method

	@DynamoDBAttribute(attributeName="user_name")
	public String getUsername() {
		return user_name;
	} //end method

	public void setUsername(String user_name) {
		this.user_name = user_name;
	} //end method

	@DynamoDBAttribute(attributeName="last_login")
	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
	public Date getLastLoginDate() {
		return last_login;
	}
	
	public void setLastLoginDate(Date last_login) {
		this.last_login = last_login;
	}

} //end class
